### ISSUE TITLE
Bee2.4 Pr12 Bugs

### ISSUE THREAD

**Issue by Slartibarty** [BenVlodgi/BEE2.4#123]
Thought I would post an issue thread with some bugs that I found.

1. The cutout block causes the map to not compile.
2. The Overgrown style uses the Clean style textures for test chamber surfaces.

That's all I've got so far.

**Comment by LautaroL20** [comment]
@TeamSpen210, In order to not making a post with this same topic, i will also leave my bug report here, as well as a small suggestion.

First of all, i will congratulate TreamSpen210 for fixing all the fizzle variations instances, now they re working like a charm:

![2015-11-08_00008](https://cloud.githubusercontent.com/assets/12244376/11022405/a17b1b6e-863c-11e5-8b30-82b62c29452c.jpg)

Now lets start listing bugs:

1. Reflection Gel still does not paint surfaces neither reflections with lazers in Clean Style.
2. All logic items and coop checkpoints exepting triggers, causes the map to not compile in Clean Style.
__________________________________________________________________________

A small but recomendable suggestion:

![suggestion](https://cloud.githubusercontent.com/assets/12244376/11022742/6558b62e-8645-11e5-8811-356c894e4ea2.jpg)

Observation:
Low quality texture on the 1/4 thin black wall (Please Click the pict to see what i mean):

![2015-11-08_00007](https://cloud.githubusercontent.com/assets/12244376/11022606/ac2ef544-8641-11e5-9d33-359eb42c8de6.jpg)

**Comment by TeamSpen210** [comment]
It's better if you actually log individual issues, that way I can close each individually. @Slartibarty, I can't seem to replicate either problem. What's the developer console error when cutout tiles crash? How exactly does Overgrown style use Clean textures - which ones?

**Comment by Slartibarty** [comment]
It seems that when you place ANYTHING except the default elements into an Overgrown style chamber it fails to compile, screenshots of the Clean style textures in the Overgrown style: ![01](http://puu.sh/lfh2U/43f0e43af4.jpg)
![02](http://puu.sh/lfh7s/486fbf969e.jpg)
The map compile log is perfectly normal, no errors.
The reason I thought the cutout block stops the map from compiling is because the overgrown style crashes whenever you add a new element.

**Comment by Slartibarty** [comment]
Don't worry about it, turns out there was an error while exporting the palette, a quick re-export fixed it!
Quick suggestion, it would be neat to have more possibilities for the cutout tile, I mean things like corner exclusive decorations (moss piles, etc)

**Comment by TeamSpen210** [comment]
That sounds like a good idea! The only problem with moss piles is that they're pretty big - it's possible they'd block portal placement, or cover up stuff like lasers on the wall.
