### ISSUE TITLE
50s style bugs

### ISSUE THREAD

**Issue by HImichun** [BenVlodgi/BEE2.4#196]
1. [ ] Missing clip on sp exit catwalk.
2. I guess missing wall and door in the same exit(when you passing thru awesome puzzle u can see black wall appearing on place where should be door).
3. Wery long delay on companion cube dropper(it opens and waits around 5 seconds).
4. [ ] Fizzler texture on bottom and top faces of fizzzzzler brush. Make them nodraw.

**Comment by LautaroL20** [comment]
2. this ussue is already reported under "Items" section:

https://github.com/TeamSpen210/BEE2-items/issues/281

**Comment by TeamSpen210** [comment]
3\. The cubedropper delays are intentional (although they shouldn't be that long). They have a delay when opening to ensure the cube drops directly downwards (so switching styles don't break puzzles). They also wait after closing to ensure the time taken to repeatedly respawn cubes is the same as Clean droppers.
4\. Valve intentionally set the top/bottom textures to that. I'll remove it between fizzlers, but not on the top and bottom - it ensures you can still see the fizzler if you're directly above or below it.

**Comment by HImichun** [comment]
1.you can jump on handrail of the catwalk and then fall into the deadly goo. singleplayer exit in 50's.

**Comment by Konclan** [comment]
If a subject wants to commit suicide at the end of a test then 60 bucks well saved. I don't see this as an issue but an enhancement!

**Comment by CrashingScience** [comment]
You forget, that guy was an astronaut war hero

**Comment by Konclan** [comment]
(The people being paid for testing were not olympians, astronauts, or war heros, that was in the 50s & 60s)

**Comment by Konclan** [comment]
I just realized my error, subjects in the 50s were not being paid 60$... my bad :P

**Comment by CrashingScience** [comment]
An astronaut war hero, from the great space war against the mantis men
