### ISSUE TITLE
So what can this new version of Bee2 Do?

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#24]
So what can this new version of Bee2 Do?

i want to know, list all of the features below, i have attempted to guess at some

- use custom styles
- adds the Wheatley style
- customization of test chamber music and voice lines
- allows usage of custom test chamber music
- custom test chamber signage

**Comment by TeamSpen210** [comment]
Lots of things!  

* Multi-game support (Tell it where Portal 2/ any sourcemod games are, and it'll install everything)
* Independently choose music, voice lines, style, elevator videos
* Customise Voice Lines (toggle whether each line is able to play)
* Improved compiler, which allows for a lot more item possibilities
* Random chamber walls stay the same across recompiles
	* A different algorithm for Old Aperture, to make that look nice
* Random item variants (Observation rooms will have different furniture, for example)
* More custom fizzlers (Paint Fizzler, Lp's Death Fizzler, etc)
* Compile-time instance switching to massively decrease entities
* Bottomless pit code to make it actually look good
* Better Sendificators (special antlines for sendificator <> laser, new logic from HMW to handle spheres and frankenturrets, 50s versions)
* Probably other things I forgot

**Comment by ellingtonisland** [comment]
I have a few more idea's

- make it possible to have test chambers play non portal 2 music (something like this: https://www.youtube.com/watch?v=n7cAyZ8jXfs) (this would creep players out if GLaDOS played this in some test chamber)
- for the bottomless pit create a variant for the overgrown style too (idea: use the intro scene in portal 2 where Wheatley carries the relaxation vault through that area and crashes it into the wall as a template for designing an overgrown pit (area where Wheatley says "not a docking station"))
- see if you can get the graphics shown in the PTI editor to change depending on the style (show dirty panels in PTI editor for overgrown style)
- see if you can figure out how to add an option to choose what character will play in a single player test chamber such as chell, bendy, or one of the two robots
- add an option that lets you choose what portal gun you have such as original, one with potatos, or the one in the upcoming mod "portal stories: Mel"

**Comment by TeamSpen210** [comment]
The Extended Relaxation Annex isn't really Overgrown style, it's more Overgrown BTS. Those maps really should use goo pits, the actual maps are 'wetter' than clean pipes because of rain, leaky pipes, etc. 

I forgot to mention the different editor models (which I am working on), like these [P1 models](http://steamcommunity.com/sharedfiles/filedetails/?id=415195927).  
I can switch the player models, I'll probably add that to the compiler options pane. I don't think the styles will change, it'd be a bit excessive making a third entry/exit room.
You need a sourcemod to change to a custom portalgun (PS: Mel, Ap Tag's paintgun). I won't add the option to have PoTaTOS - it wouldn't make any sense story-wise. (Especially if regular GLaDOS is present.) You can choose what portals can be fired though (No gun, both, blue only, orange only).

**Comment by TeamSpen210** [comment]
For custom music, it's not difficult to make a package to load it with. You need 3 files in a zip file:  
**info.txt**

    "ID"		"ID_FOR_PACKAGE"
    "Name"		"The Package Name"
    "Music"
    	{
    	"ID"			"SOME_UNIQUE_ID"
    	"Name"			"Put The Full Name Of The Song Here"
    	"ShortName"		"Shorter Name"
    	"Icon"			"music/music_icon.png"
    	"Authors"		"Song Author, Your Name Here"
    	"Description"	"Information about the song."
    	"SoundScript"	"sound/whatever_your_music_is.wav"
    	}
**resources/BEE2/music/music_icon.png**: A 96x96 png image to show in the BEE2.
**resources/sound/whatever_your_music_is.wav**: The wav file for your music (You'll need to do some processing to get it to loop correctly.)

See [BEE2-items/packages](https://github.com/TeamSpen210/BEE2-items/tree/master/packages/music) for all the defintions for Valve's music.
