### ISSUE TITLE
Autoportals/Cube Drop Delay

### ISSUE THREAD

**Issue by Gimzie** [BenVlodgi/BEE2.4#254]
When activating an autoportal with a button, floor button, or laser catcher, the portal opens after 3 seconds. Also, cubes in Old Aperture have a delay before they drop. Although the cube issue isn't a major issue, the autoportal problem can mess up a lot of timing maps. (*cough*mine*cough*)

**Comment by LautaroL20** [comment]
Hello, Gimzie. This is the section to report bugs involved with the Bee2.4 interface rather than "Items".

To report bugs related to any items, post them here: https://github.com/TeamSpen210/BEE2-items/issues

Respect to the cube drop delay on the Old Apertures, it was already reported into the items section:
"Cube Dropping" takes too long (5 Sec) and the "Visual Re-generation" is completely "Unreal"
https://github.com/TeamSpen210/BEE2-items/issues/376

**Comment by Gimzie** [comment]
Ah, sorry about that.

**Comment by Konclan** [comment]
If this bug is already reported, Then the issue should be closed
