### ISSUE TITLE
Nonconnection Antline (Decoration and/or Logic)

### ISSUE THREAD

**Issue by Coolasp1e** [BenVlodgi/BEE2.4#277]
Would be used in Underground and Overgrown. A placeable item that interrupts the antline (Or just a fake antline) that prevents one item connecting to another. There would be a break in the antline where the item is placed (Or a randomly generated break with fake antline) so the object doesn't work. Useful for broken maps with a different solution to the puzzle than the intended one.

**Comment by TeamSpen210** [comment]
You can do this with an AND gate - insert it between the input and output, and it'll give you 1 block of space. Connect a hidden button or something also with antlines disabled to prevent the target activating.

In Overgrown and Old Aperture styles, antlines do have random elements appear broken - sections set to the "off" texture. Realistically, chamber damage wouldn't disable the target object just because the antlines were broken or missing - they're probably on seperate circuits.
