### ISSUE TITLE
Overgrown entry/exit varients

### ISSUE THREAD

**Issue by Konclan** [BenVlodgi/BEE2.4#281]
Some overgrown entry and/or exit variants with moving panels trying to fix themselves. Also some panels that are smacking walls because they are corrupted.

**Comment by TeamSpen210** [comment]
This isn't actually Overgrown style, it's Reconstructing style. Overgrown style is set when the facility is in emergency power mode, and most things are turned off. For that reason panel arms (except for ones critical to the puzzle) are limp and off. Reconstructing style is set after GLaDOS reawakens, and has the panels moving around trying to fix the chamber. It also has an absence of plants entirely, since it's much further down underground.

**Comment by Konclan** [comment]
Oh ok, so will you make a reconstruction style in the future?

**Comment by TeamSpen210** [comment]
Yes.
