### ISSUE TITLE
some final implementations needed for bee2

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#30]
here are some final implementations that should go into bee2. these will give it TOTAL test chamber customization. good luck, I hope you can implement some of these. ben agrees with me on giving the player an option to choose the exit and entrance elevator and hallways etc.

- add an option to select a common audio file for custom music and have bee2 automatically convert it to the right format and everything and assign it all the correct properties and implement it right into the test chamber.
- add an option to select a common audio file for a custom voice line and have bee2 automatically convert it to the right format and everything and assign it the correct properties and implement it into the test chamber.
- add an option to select a common video file for a custom elevator video and have bee2 automatically convert it to the right format and everything and assign it the correct properties and implement it into the elevator of your test chamber.
- (ben agree's with me on this one) add an option that allows you to choose what entrance and exit elevators and elevator hallways your test chamber uses if you don't want them randomized, I recently saw a video of backstock ben put up and he has created an elevator with no walls and ceiling outside the test chamber in a Wheatley like style that uses a diversity tube ride to take you to the next test chamber. an elevator like this would be good for a modernized clean style with bottomless pits and open walls and ceilings with multiverse cave as the narrator.

**Comment by TeamSpen210** [comment]
It's not possible AFAIK to pack videos into a map, so you can't have custom elevator videos. The only reason they're set in package files is it makes it easier to write. I'm not going to make automatic package generators, there's just a fair bit too much for users to set. 
 
 I do have a mechanism to choose elevator variants, it's part of the style though - you can't mix a 50s sphere with Clean corridors. That wouldn't work at all anyway since the worldportal styles would mess up (bare corrdor vs clean door). I can though make a Clean style vactube entry/exit, and I probably will (besides the Aperture Tag one.)
I made a separate issue (#31) for the choosing of corridor variants.
