### ISSUE TITLE
BEEMOD Suggestions

### ISSUE THREAD

**Issue by jccreszMinecraft** [BenVlodgi/BEE2.4#46]
So, I have a few suggestions for the BEEMOD team.
1. Angle-able panels on a piston arm
2. Possible tracks to cinematic-ally switch an testing element to another, like when GLaDOS is repairing the facility and switches a pellet element set for a laser set.
3. Item that can control the type of chamber entrance/exit. I've noticed for example there are different types of chamber entrances/exits, and I would like to be able to customize them.
4. Make it possible to rotate sections of the chamber similar to the Overgrown style application in the game.
5. Curve brush items? Maybe these aren't practical but they might look nice in chamber design.
6. Floor tracks
7. Possible panel decoration that opens to reveal the outside of a test chamber. Referencing one of Ben's streamed chamber features.
8. 1/4 Wall texture selector... Timer thingie based?
9. Wall feature visuals? Ability to put Wall features on the same block but different sides?
10. Piston arms / panels that can have their angle adjusted incrementally.
11. 1/2 block vertical observation room like in the "broken" test-chamber in portal 1?
12. Element types on piston arms
13. Retractable Lasers/catchers/relays/Funnels/droppers
14. Sliding panel that uncovers an element 
15. Rotating Fizzler? Rotating Hard Light Bridge?
16. Water. Lakes of water. Harmless Toxic goo really.
17. Ability to enable a wind entity (to affect leaves for instance in the Overgrown Style or just have a wind sound).
18. Animation panel that can move backwards, slide in a set direction, and be replaced by something else. Same idea as (2)
19. Enable/disable sparks in broken styles
20. WorldPortal Doors do not work correctly/are difficult to get working/understand
21. Chamberlocks will trap you inside if their input was decided by something going through a portal, like a laser.
22. Living panels do not inherit gel properties.
23. a few themes will neglect to spawn dropperless cubes, like art therapy and refurbished
24. New BEEMOD icon made by me (http://www.mediafire.com/view/od8a81mmjm5i6f1)
![beemodlogo1](https://cloud.githubusercontent.com/assets/9320772/7996402/02eb65c2-0aee-11e5-81b6-ca08692ba58c.png)
25. Add Bisqwit's 512x256 Observation rooms?
26. Portivity gun (Gravity Gun + Portal Gun) Found on the TWP website.
27. wall decal item that changes type according to a timer adjuster
28. Make the retractable button have a default of 01 instead of 03, similar to the instant pedestal button.
29. Organize your portal spawner items. Some do not link to others in the map.
30.  Item to change skybox type as well as skybox related item overhauls
31. Theme suggestion: BTS, kind of like a cave sphere entrance elevator with a path to the chamber, lots of other tests' exteriors visible around the chamber you are entering. Kind of like the scene before you go and beat wheatley, minus the crumbling.
32. Vacuum tubes do not allow the map to compile and usually crashes the game.
33. Catwalks need to be able to float in the air/and/or have an ability to change models via timer. Also catwalk stairs.
34. Antlines routing funny on either plain doors or sendificators. possible a few other items too.
35. Lighting does not look right on some elements such as portalable piston panels and large live panels.
36. Better camera placement (They appear very buggy/weird looking on their mounts and sometimes look the opposite direction the player is)
37. Some items lack images in the BEEMOD interface
38. Deletion and creation of palettes, ability to create own categories in the sort by..
39. Half panels not able to be in the same voxel area as toxic goo? also there could be a possible input here to open it...
40. Half panels cannot be put on the same block and antlines have a tendency to route UNDER them. also portals may bug out and cover a corner of the black side.

**Comment by TeamSpen210** [comment]
1. Ok, I'll probably lock them so they don't change angle though.
2. I don't think this'd work well in the BEE2, it's more story-oriented than puzzle-oriented
3. I'm going to add this to the 'compiler' pane of the BEE2 viewer. There are 7 entry rooms, and 4 exit rooms + 4 coop exit rooms. I will be adding additional variants to other items in certain styles (for example there are 3 Clean small obs rooms with different furniture). To swap those delete and replace the item. 
4. This'd be really complicated, and could possibly break a lot of maps easily. (I'd have to calculate all the new coordinates for every brush and instance, fill in the gaps between brushes and make sure it only applies to some sections.)
5. Ok.
6. What would this do?
7. In the various BTS / Wheately / Destroyed styles, this will probably be part of the wall feature items.
8. I don't think it's needed to be able to tweak blocks at the ¼ tile level.
9. I can't really allow you to put wall features on multiple sides, but I'll probably make a corner wall feature item.
10. I'm not sure how this is different to 1.
11. In the Portal 1 style, all the observation rooms are this size.
12. I've made piston versions for a few different items (laser relays, autoportals). I might do it for more, but it isn't really possible to automatically create one for every item.
13. Maybe I'll make an item designed to be placed in front of these which opens, although you can do that already with angled panels.
14. A sliding panel might be nice, like in one of the Coop Mass and Velocity courses.
15. I don't think fizzlers work very well if they're moving. I will want to make a rotating light bridge, or at least one that swaps between vertical/horizontal.
16. The Coop players are hardcoded to do an explosion animation on contact with water (leaving them in a very weird dead state if they don't get killed after), so this isn't really possible.
17. The overgrown skybox should have a wind entity already, though it isn't user controllable.
18. This kind of cinematic stuff isn't really the goal of the BEE2.
19. I'm now able to add random variants to every item, so the amount of damage will probably be toned down quite a lot (only some antlines + obs rooms will flicker).
20. I'm completely re-doing how these work internally, since the current method is a workaround for not having a custom compiler,
21. I need to redo the logic so they can't do this anymore.
22. I'll probably redo these to use the custom compiler, fixing that in the process.
23. That's a bug, which I'll need to fix of course.
24. @BenVlodgi, what do you think of this icon?
25. They will be copied over to the BEE2.4, and I'll make a bunch of styled versions eventually.
26. I don't think I'll add this for now.
27. This'll probably be added in some form, but slightly more generically so it can match styles (IE showing arrows, 1-4 dots, exit). The black/white signage isn't appropriate for 50s or BTS style, for example.
28. This is done, and you'll be able to set the default for any item property.
29. I am fixing this when I re-add the items.
30. Skyboxes are chosen in the BEE2 at the same time as you choose voice lines, styles and items. I've been improving how they appear significantly.
31. This'll be the appearance of Wheately Destroyed, and Art Therapy chambers.
32. I'm majorly redesigning how these work, and they'll work properly.
33. My plans for catwalks will let you have midair catwalks, stairs, etc all out of 1 item.
34. That's one reason why I made the antline magnet and chamberlock items, it's not really possible to fix the BEE door item antlines. I'll need to fix the sendificator antlines eventually.
35. Lighting in the Source engine is static, so these can't change lighting. Try and ensure the start and end positions have the same lighting with light strips or similar.
36. I'll fix that if I can find when it happens.
37. I haven't made icons for those items yet, it's temporary.
38. I'm redoing the sorting field so it's easier to do this sort of thing, and you can make your own palettes (buttons above export, or in the palette menu).
39. This is something that's sort of hardcoded, every item which collides with something can't be placed in goo (other than piston platforms, track platforms, angled panels). I might make them moveable, it wouldn't have downsides anymore.
40. This is due to the item's collisions, but I might tweak the item so it's possible without them overlapping each other (switching one of the instances to only be on one side). I'll fix the antline thing.

**Comment by jccreszMinecraft** [comment]
Oh wow i'm bad at english in some places.
for 39 i meant the kind of half panel that extends the surface 1/2 a voxel
and I think you understood what I meant for 40, i meant the 1/2 black 1/2 white panel item...

**Comment by TeamSpen210** [comment]
The corner thing is a bug with Portal 2 (it only seems to check if the exact centre of the portal is on white surfaces, although portal bumpers can help fix it.

**Comment by jccreszMinecraft** [comment]
Oh gosh sorry for 10 I meant rotation like your rotating faithplate. I apologize

**Comment by TeamSpen210** [comment]
The main problem with making panels like that rotate is that the panel arm items aren't really designed to be able to rotate - they'd crash into the walls. I might make the panel retract fully, play some mechanical sounds, and then open in the new orientation.

**Comment by jccreszMinecraft** [comment]
Dang, you're getting to these pretty fast. I have one more to fire at you and i'll leave you alone for the night.

Some of the panel animations clip horribly into the floor or whatever surface they are mounted on. What's up with that?

**Comment by TeamSpen210** [comment]
In which items? - I really don't have anything to do with Bisquit's panel items, for example.

**Comment by BenVlodgi** [comment]
24. This is a cute icon, and it does fit the theme of the BEEMOD, it really does look like what I was looking for for the BEE1. However someone else did create a new icon for the BEEMOD2 which I think we'll stick with. 
https://raw.githubusercontent.com/BenVlodgi/BEE2.4/a83d566e68b5b30d91d02305e1befed427cdc331/bee2.ico

**Comment by jccreszMinecraft** [comment]
#sadface

**Comment by ellingtonisland** [comment]
i have some more

- make it so bee2 changes the default graphics used on the wall panels in PTI (the ones you pull and push to shape out the test chamber) when the style is changed (such as show overgrown panels in the PTI graphics instead of clean ones when using a overgrown style)
- make portal 1 camera's follow the player
- where's the voice line selection editor?

**Comment by TeamSpen210** [comment]
I do know how to modify the editor textures, but I want to figure out a way to avoid potentially breaking games that it's copied into. 

For the Portal 1 cameras and turrets, I need someone who is a good modeller to modify the original models so they have the animations of the Portal 2 counterparts. Otherwise they won't actually do anything.

Most of the voice lines aren't actually done, so they're empty. Select Cave (50s) or Clean GLaD0S, and then click the gear next to the voiceline picker.

The reason why I made the separate panes is to allow users to rearrange the the sections to suit their preferences, or hide windows they aren't using. It also helps let the BEE2 fit in smaller screen sizes if needed, since I think it's a little too complex as one window,

**Comment by ellingtonisland** [comment]
clicking the gear next to the voice line picker does nothing

**Comment by Fazbear189** [comment]
Just make it so you get an error when you use the water in a co-op map.
