### ISSUE TITLE
Dropperless custom cube items

### ISSUE THREAD

**Issue by jccreszMinecraft** [BenVlodgi/BEE2.4#53]
I've noticed in the older releases (not bee2.4) that some addons such as the portal deflection cube did not have a dropper. I suggest that in the future, we can put a custom cube item on the pallet and have a checkbox on whether or not it should have a dropper, or completely mimic the original PTi's cube selection tool.

**Comment by TeamSpen210** [comment]
Unfortunately, it's not really possible to create custom items for these linked things (faith plates <> targets, paint dropper <> paint splat, cube dropper <> cube). When you place one, the PeTI is coded to always place a copy of the other item type. This is OK for faith plates, since the target doesn't need to change - but for cubes you'll end up with just a regular cube dropper. 

When I re-add them, items should have separate dropper and dropperless variations.
