### ISSUE TITLE
Weird CheckerBox Icons and other

### ISSUE THREAD

**Issue by xDadiKx** [BenVlodgi/BEE2.4#55]
So I choose my own items. Styles and voice. And I export it. For e.x. yea?
So I go to the InGame editor. And I get some weird checkerbox icons in my items menu. So I don't place anything down. And I play the test chamber. And I get a error, meaning I can't play my test chamber. So I place a item down, and it is still the same error I got.

Did I place BEE 4.0.4 in a wrong place? If so. Tell me, and I will again try to do this. And if this happens again, once I placed it to the right place in the files. Where you guys tell me. It is most likely a bug.

Thanks.

**Comment by ellingtonisland** [comment]
there missing texture errors for the palate because the bee2 is still in very early dev

**Comment by xDadiKx** [comment]
Do you mean the latest bee 2? The bee 4.0.4?

**Comment by BenVlodgi** [comment]
@xDadiKx This is the issues page for the latest version of the BEE2 which is currently BEE2.4.0.4 also known as the BEE2.4 prerelease 4
And to answer your question, yes, this new version is still in development which is why we called it a pre-release :)

The Pink checkerbox texture means the visual resource wasn't loaded (probably doesn't exist where its being looked for)

You can place the pre-release file anywhere.... personally I just have that folder on my desktop, it doesn't matter... it just matters that it knows where to export the files to

**Comment by ellingtonisland** [comment]
this is caused by missing assets
