### ISSUE TITLE
Can catwalks turn corners? Possible Bug?

### ISSUE THREAD

**Issue by harritron2k2** [BenVlodgi/BEE2.4#82]
I added a catwalk to my map yesterday and made it turn a corner, with it being the same height, but when I combiled the map, it just had the ends of the catwalks, nothing else. Can they turn corners or is this just a bug?

**Comment by TeamSpen210** [comment]
How did you make it turn a corner? Catwalks must be in straight lines horizontally, so a corner needs 3 catwalk pieces. You can have any junction - corners, t-intersections, cross pieces, or open ends (with 1 connection). For stairs, the horizontal distance must be at least twice the vertical distance (otherwise the stairs wouldn't fit).

**Comment by harritron2k2** [comment]
Ok, never mind then. I just placed a gap between the catwalks and it works just fine
