### ISSUE TITLE
Is it possible? 

### ISSUE THREAD

**Issue by xDadiKx** [BenVlodgi/BEE2.4#88]
Is it possible to place a door, and a trigger once, that opens the door. And another trigger once that closes the door?

**Comment by TeamSpen210** [comment]
The logic for this would end up a little complex. You need to invert the closing trigger with a NOT gate, and feed that into the door (optionally through an AND gate to manage antlines). Since this is a bit of complicated logic (and it's possible to do various things to hold a door open) I made my SP checkpoint item. That's in the BEE2, I haven't added the styled versions yet though. It also includes a fizzler, since you want that if you're going to permanently lock a door.

**Comment by xDadiKx** [comment]
Well, I have managed to do it on my old maps. But I forgot, so it is possible?

**Comment by TeamSpen210** [comment]
Use a NOT hate on the closing trigger, and connect that and the open trigger to the door (set to start locked).
