### ISSUE TITLE
Development update?

### ISSUE THREAD

**Issue by harritron2k2** [BenVlodgi/BEE2.4#89]
It's been a while since anything happened on here, can you please maybe give a peak of what will be on the next pre-release? Also please add bottomless pits to all styles in the next few releases. Take your time, I'm not rushing you.

**Comment by TeamSpen210** [comment]
The main 2 things I've done are fix the voice lines so they actually play, and add the portalgun logic so you can spawn with single-portal devices. Since I'm always commiting to GitHub, you can actually check these two links to see exactly what changes have been done since the last release. 

* https://github.com/TeamSpen210/BEE2-items/compare/dev
* https://github.com/BenVlodgi/BEE2.4/compare/dev

**Comment by harritron2k2** [comment]
Ok thanks for that, I just didn't know why there went any issues in the past 2nweeks until today.
