### ISSUE TITLE
enhancements for voice selection options

### ISSUE THREAD

**Issue by ellingtonisland** [BenVlodgi/BEE2.4#93]
i have a idea for some ways to enhance what you can do with the voice line selection toolbox, use checkboxes to choose what lines will play in a map if it has mid chamber dialogue or multiverse cave such as

- per item checkboxes to choose if lines will be played based on if you have a certain item in your map like when glados says "we have warehouses full of the things" every time you destroy a cube.
- a checkbox that will make a line play if you stay in a test chamber long enough (such as that one glados says about "you are listening to me, you don't have to go that slow" but more like a custom line in one of mine would say "looks like my little test has you stumped, good, want a hint, well... (soup nazi like voice) NO HINTS FOR YOU!!!" 
- move the checkboxes for multiverse cave, and suppress mid chamber dialogue into the menu that will come up when you click the gear next to the voice selection menu.

**Comment by TeamSpen210** [comment]
* This is already there, just uncheck things on the "mid" tab.
* I think I might add this to Wheatley's voicelines, but not other characters. Since different chambers have different lengths (one might take 2 minutes, one might take an hour) I wouldn't be able to time quotes to play at the right time. It'd be fine though if Wheatley's impatient, since he's not supposed to be good at managing anything.
* These are global options, unlike the options for each voice line. You can unckeck things in the nid tab to disable a particular voice line's mid-chamber quotes. Multiverse Cave is unrelated to the extra voicelines.

**Comment by ellingtonisland** [comment]
i want you to add a option to <b>(choose if it will be played)</b> play a quote if you spend a long enough time in a test chamber to all characters. this is purposefully created for the creation of test chambers are designed to be hard and stump the mind <b>(there is the option (checkbox or something) to turn it off such as for easy test chambers)</b>
