### ISSUE TITLE
Reimplement Addons items

### ISSUE THREAD

**Issue by TeamSpen210** [BenVlodgi/BEE2.4#98]
(Moved to TeamSpen210/BEE2-items#95)

**Comment by ellingtonisland** [comment]
i have a few suggestions for you @TeamSpen210 

- remove the laser music and music items and make laser music, catapult music, to be merged with their songs that the new bee2 allows selection of.
- what was the ditch item for, it was pretty much useless to me.
- for the world portal door add a 1 voxel wide surface division field.
- merge slow crusher into original crusher
- fix auto portals so if three orange or blue ones were in a test chamber connected to buttons the other two would reset and close when you pressed the button to open one of them.
- rename the custom 50's laser field you created to "electric fence" because that is what it looks like.
- make it so recessed fizzlers work like normal fizzlers and can be sized to any size easily like glass and grating can.
- make the ceiling light work like glass/grating so you can size it to anything you want and it will generate instances similar to the logic your using to make a bottomless pit and depending upon the style such as for overgrown it could generate a small hole in the ceiling or a giant one.
- turn down the volume on shredders, it still drowns out everything, in the campaign with wheatley the shredder is much quieter.
- fix the bugs with the conveyor belt so it can be painted and light is calculated on it properly.
- implement breakable glass, but make it so you can size it to anything you want like regular glass or grating, and if a bomb would hit one, no matter the size, the whole thing would shatter.
- remove the platform from the bottom of the diversity vent that came with the original early bee
- combine all three variants of the lightstrip into one item and make the proper cold variant unlike the one on thinking with portals that looks purple.

**Comment by TeamSpen210** [comment]
* That actually was my intention. I'm thinking about implementing compiler logic to detect multiple laser catchers hooked together, and play music when they activate.
* The ditch item is most useful in maps with Edgeless Safety Cubes. Put it under the cubedropper, and it'll stop the ball from wandering around. 
* I don't think I want to include the Surface Division Fields in the BEE2 - they aren't 2 pieces in a pair.
* Slow Crushers are totally different to regular ones. 
* If this still happens, it's a bug. If you simultaneously activate two same-colour portals though, I can't really do anything about that.
* I can't make extendable recessed fizzlers and ceiling lights. Glass/gratings extend totally differently, and track platforms would collide with other items often.
* I will be redesigning the logic for conveyor belts - with the custom compiler, I can make them work exactly as they do in the campaign.
* I'll probably implement two different versions of breakable glass, one multi-paned and one which breaks individually for each block.
* I have some ideas for the diversity vent platform, it's necessary to have a floor there however.
* Ok, I'll add an additional very-cold light.
